name    'pdxcat-group'
version '0.0.1'
source 'git://github.com/pdxcat/pdxcat-group'
author 'Reid Vandewiele <marut@cat.pdx.edu>'
license 'Apache'
summary 'gpasswd provider'
description 'Adds a group provider "gpasswd"'
project_page 'https://github.com/pdxcat/pdxcat-group'
